{{- range $name, $ingressRoute := .Values.ingressRoutes }}
{{- if $ingressRoute.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}-ingressroute
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    app: {{ $name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
spec:
  entryPoints:
  {{- range $ingressRoute.entryPoints }}
  - {{ . }}
  {{- end }}
  routes:
  {{- range $ingressRoute.routes }}
  - match: {{ .match }}
    kind: {{ .kind | default "Rule" }}
    {{- if .priority }}
    priority: {{ .priority }}
    {{- end }}
    services:
    {{- range .services }}
    - name: {{ $.Release.Name }}-service
      port: {{ .port }}
      {{- if .weight }}
      weight: {{ .weight }}
      {{- end }}
      {{- if .strategy }}
      strategy: {{ .strategy }}
      {{- end }}
      {{- if .passHostHeader }}
      passHostHeader: {{ .passHostHeader }}
      {{- end }}
    {{- end }}
    {{- if .middlewares }}
    middlewares:
    {{- range .middlewares }}
    - name: {{ $.Release.Name }}-{{ .name }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if $ingressRoute.tls }}
  {{- if $ingressRoute.tls.enabled }}
  tls:
    {{- if $ingressRoute.tls.certResolver }}
    certResolver: {{ $ingressRoute.tls.certResolver }}
    {{- end }}
    {{- if $ingressRoute.tls.domains }}
    domains:
    {{- range $ingressRoute.tls.domains }}
    - main: {{ .main }}
      {{- if .sans }}
      sans:
      {{- range .sans }}
      - {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if $ingressRoute.tls.secretName }}
    secretName: {{ $ingressRoute.tls.secretName }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }} 