{{- range $name, $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    app: {{ $name | replace "-secret" "" }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
type: {{ $secret.type | default "Opaque" }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- if $secret.stringData }}
stringData:
  {{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }} 