name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: Setup Clean gh-pages Branch
        run: |
          git checkout -B gh-pages
          git pull origin gh-pages --ff-only || true
          git rm -rf .
          git clean -fxd
          git commit --allow-empty -m "Reset gh-pages branch"
          git push --force origin gh-pages
          git checkout main
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
          config: cr-config.yaml
          
      - name: Generate and Push index.yaml
        run: |
          if [ -d ".cr-release-packages" ]; then
            mkdir -p .cr-index
            helm repo index --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ .cr-release-packages --merge .cr-index/index.yaml || true
            git checkout gh-pages
            cp .cr-release-packages/index.yaml index.yaml || true
            git add index.yaml
            git commit -m "Update index.yaml" || true
            git push origin gh-pages
          fi
          
      - name: Verify gh-pages
        run: |
          echo "Verificando se a branch gh-pages foi atualizada corretamente"
          git fetch origin gh-pages || echo "Branch gh-pages ainda não existe"