name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: Package Charts
        run: |
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" -d .cr-release-packages/
              echo "Packaged $(basename $chart)"
            fi
          done
      
      - name: Create GitHub Pages
        run: |
          # Cria uma diretório temporário para gh-pages
          mkdir -p gh-pages
          
          # Copia os pacotes para a pasta gh-pages
          cp .cr-release-packages/*.tgz gh-pages/
          
          # Cria arquivo .nojekyll para evitar processamento Jekyll
          touch gh-pages/.nojekyll
          
          # Gera o index.yaml na pasta gh-pages
          cd gh-pages
          helm repo index --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ .
          
          # Volta para o diretório raiz
          cd ..
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          force_orphan: true
          
      - name: Cleanup
        run: |
          rm -rf gh-pages
          rm -rf .cr-release-packages