name: Test Workflow
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    environment: ci/cd
    steps:
      - name: Check runner info
        run: |
          echo "Hello from self-hosted runner!"
          echo "Hostname: $(hostname)"
          echo "OS: $(uname -a)"
          echo "Working directory: $(pwd)"
          echo "Directory contents:"
          ls -la
      - name: Verify environment variables using GitHub contexts
        env:
          # Adicione aqui os nomes das suas variáveis de environment
          DATABASE_USER: ${{ vars.DATABASE_USER }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          # Adicione outras variáveis de environment conforme necessário
        run: |
          echo "============== ENVIRONMENT VARIABLES VIA GITHUB CONTEXTS =============="
          echo "DATABASE_USER: $DATABASE_USER"
          echo "DATABASE_PASS: $DATABASE_PASS"